"""create project assignment table

Revision ID: 2463ad20eccd
Revises: b22e9fb95fc2
Create Date: 2026-09-21 11:02:24.293578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2463ad20eccd'
down_revision: Union[str, Sequence[str], None] = 'b22e9fb95fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'employee_id', name='uq_project_employee_assignment')
    )
    op.create_index(op.f('ix_project_assignments_employee_id'), 'project_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_project_assignments_project_id'), 'project_assignments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_assignments_project_id'), table_name='project_assignments')
    op.drop_index(op.f('ix_project_assignments_employee_id'), table_name='project_assignments')
    op.drop_table('project_assignments')
    # ### end Alembic commands ###
