"""create_work_reports_table

Revision ID: 4cbb90b78c13
Revises: f5819d42ab17
Create Date: 2026-09-22 22:50:46.531919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbb90b78c13'
down_revision: Union[str, Sequence[str], None] = 'f5819d42ab17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tasks_completed', sa.Text(), nullable=False),
    sa.Column('plans_for_tomorrow', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='work_report_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_work_reports_employee_date')
    )
    op.create_index('ix_work_reports_date_status', 'work_reports', ['work_date', 'status'], unique=False)
    op.create_index(op.f('ix_work_reports_employee_id'), 'work_reports', ['employee_id'], unique=False)
    op.create_index('ix_work_reports_employee_status', 'work_reports', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_work_reports_project_id'), 'work_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_work_reports_status'), 'work_reports', ['status'], unique=False)
    op.create_index(op.f('ix_work_reports_work_date'), 'work_reports', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_reports_work_date'), table_name='work_reports')
    op.drop_index(op.f('ix_work_reports_status'), table_name='work_reports')
    op.drop_index(op.f('ix_work_reports_project_id'), table_name='work_reports')
    op.drop_index('ix_work_reports_employee_status', table_name='work_reports')
    op.drop_index(op.f('ix_work_reports_employee_id'), table_name='work_reports')
    op.drop_index('ix_work_reports_date_status', table_name='work_reports')
    op.drop_table('work_reports')
    # ### end Alembic commands ###
