"""add performance service

Revision ID: f6cff5de584c
Revises: b8c7d6e5f4a3
Create Date: 2026-09-23 15:57:06.599279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6cff5de584c'
down_revision: Union[str, Sequence[str], None] = 'b8c7d6e5f4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='performance_goal_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_goals_emp_status', 'performance_goals', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_performance_goals_employee_id'), 'performance_goals', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_goals_status'), 'performance_goals', ['status'], unique=False)
    op.create_table('performance_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('review_period', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'COMPLETED', name='performance_review_status'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_reviews_emp_period', 'performance_reviews', ['employee_id', 'review_period'], unique=False)
    op.create_index(op.f('ix_performance_reviews_employee_id'), 'performance_reviews', ['employee_id'], unique=False)
    op.create_index(op.f('ix_performance_reviews_review_date'), 'performance_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_performance_reviews_review_period'), 'performance_reviews', ['review_period'], unique=False)
    op.create_index(op.f('ix_performance_reviews_reviewer_id'), 'performance_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_performance_reviews_status'), 'performance_reviews', ['status'], unique=False)
    op.create_index('ix_performance_reviews_status_date', 'performance_reviews', ['status', 'review_date'], unique=False)
    op.create_table('review_category_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['performance_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'category', name='uq_review_category')
    )
    op.create_index(op.f('ix_review_category_ratings_review_id'), 'review_category_ratings', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_category_ratings_review_id'), table_name='review_category_ratings')
    op.drop_table('review_category_ratings')
    op.drop_index('ix_performance_reviews_status_date', table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_status'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_reviewer_id'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_review_period'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_review_date'), table_name='performance_reviews')
    op.drop_index(op.f('ix_performance_reviews_employee_id'), table_name='performance_reviews')
    op.drop_index('ix_performance_reviews_emp_period', table_name='performance_reviews')
    op.drop_table('performance_reviews')
    op.drop_index(op.f('ix_performance_goals_status'), table_name='performance_goals')
    op.drop_index(op.f('ix_performance_goals_employee_id'), table_name='performance_goals')
    op.drop_index('ix_performance_goals_emp_status', table_name='performance_goals')
    op.drop_table('performance_goals')
    # ### end Alembic commands ###
